language: node_js

node_js:
 - "0.10"

addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

install:
 - npm install

before_install:
 - npm install -g grunt-cli
